stages:
  retrieve_cve_info:
    cmd: python3 dependency_search/retrieve_cve_info.py data/published_cve_df_filename
      data/unique_cve_info-cvss_cwe.parquet
    deps:
    - data/published_cve_df_filename
    - dependency_search/retrieve_cve_info.py
    outs:
    - data/unique_cve_info-cvss_cwe.parquet
