stages:
  retrieve_cve_dates:
    cmd: python3 dependency_search/retrieve_cve_dates.py data/cve_df_filename 
      data/published_cve_df_filename
    deps:
    - data/cve_df_filename
    - dependency_search/retrieve_cve_dates.py
    outs:
    - data/published_cve_df_filename
  retrieve_cve_info:
    cmd: python3 cve_information/retrieve_cve_info.py data/published_cve_df_filename
      data/unique_cve_info-cvss_cwe_etc.parquet
    deps:
    - data/published_cve_df_filename
    - cve_information/retrieve_cve_info.py
    outs:
    - data/unique_cve_info-cvss_cwe_etc.parquet
  retrieve_project_info:
    cmd: python3 projects_stats/retrieve_metadata_from_WoC_mongodb.py data/cve_df_filename
      data/unique_project_info.parquet
    deps:
    - data/cve_df_filename
    - projects_stats/retrieve_metadata_from_WoC_mongodb.py
    outs:
    - data/unique_project_info.parquet
  merge_cve_dates:
    cmd: python3 dependency_search/merge_cve_df_with_published_cve_df.py data/cve_df_filename
      data/published_cve_df_filename data/commits_with_published_cve_df
    deps:
    - data/cve_df_filename
    - data/published_cve_df_filename
    - dependency_search/merge_cve_df_with_published_cve_df.py
    outs:
    - data/commits_with_published_cve_df
